language: node_js
node_js:
  - "10.16.3"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules

before_script:
  - cd frontend
  - npm install -g @angular/cli
  - npm install

  - cd ../backend
  - npm install
  - cd ..

script:

  - npm run test-backend

  - npm run lint
  - npm run test-frontend
  - npm run build
  
